### ISSUE TITLE
Lucee 5's GetHTTPRequestData() cannot take an argument

### ISSUE THREAD

**Issue by brianharcourt** [cfchris/Relaxation#27]
Deploying this in a Lucee 5 environment and get `lucee.transformer.bytecode.statement.ExpressionAsStatement cannot be cast to lucee.transformer.bytecode.statement.tag.TagComponent`
when `false` is passed to `GetHTTPRequestData()`

Not sure how/if it's worth detecting the environment to decide whether to pass the argument.  I've just edited the code locally.

**Comment by cfchris** [comment]
If you want to maintain a local copy, that is fine. 

I would also be fine if you wanted to fork the repo and put up a PR with a fix that detects the env and doesn't pass that argument for Lucee.

(I am going to push up some some minor changes probably today. So, you may want to try and diff them into your local copy OR fork the repo and add your addition to it and put up a PR.)

**Comment by brianharcourt** [comment]
D'oh!  Of course!  Fork and PR  :/   It's on my todo list.  Thanks!

**Comment by cfchris** [comment]
Looks like they (Lucee Dev) fixed the incompatibility. 

I see this issue is "Deployed". https://luceeserver.atlassian.net/browse/LDEV-1481

**Comment by cfchris** [comment]
Any update on this? Is GetHTTPRequestData() "fixed" (to be compatible w/ ACF) in Lucee now?

**Comment by cfchris** [comment]
Issue resolved in Lucee.
